//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Web.Services.WebServiceAttribute(Namespace="http://vega.vector.at")]
[System.Web.Services.WebServiceBindingAttribute(Name="VegaServiceV2Soap11Binding", Namespace="http://vega.vector.at")]
public abstract partial class VegaServiceV2 : System.Web.Services.WebService {
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getUsedAndCommissionVehicles", RequestNamespace="http://vega.vector.at", ResponseNamespace="http://vega.vector.at", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
    public abstract VehicleInvoice[] getUsedAndCommissionVehicles([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string birNumber, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string fromDate, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string toDate);
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:checkBIRNumber", RequestNamespace="http://vega.vector.at", ResponseNamespace="http://vega.vector.at", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
    public abstract UserInfo checkBIRNumber([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string birNumber);
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getVersion", RequestNamespace="http://vega.vector.at", ResponseNamespace="http://vega.vector.at", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
    public abstract string getVersion();
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getNewVehicles", RequestNamespace="http://vega.vector.at", ResponseNamespace="http://vega.vector.at", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
    public abstract VehicleInvoice[] getNewVehicles([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string birNumber, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string fromDate, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string toDate);
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:checkBIRNumbers", RequestNamespace="http://vega.vector.at", ResponseNamespace="http://vega.vector.at", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
    public abstract UserInfo[] checkBIRNumbers([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string birSearchString);
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getWorkOrders", RequestNamespace="http://vega.vector.at", ResponseNamespace="http://vega.vector.at", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
    public abstract VehicleInvoice[] getWorkOrders([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string birNumber, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string fromDate, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string toDate);
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getAllBlockedCustomers", RequestNamespace="http://vega.vector.at", ResponseNamespace="http://vega.vector.at", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
    public abstract Customer[] getAllBlockedCustomers([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string birNumber);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dataobjects.vega.vector.at/xsd")]
public partial class VehicleInvoice {
    
    private Customer customerField;
    
    private string errorCodeField;
    
    private string errorTextField;
    
    private double invoiceAmountField;
    
    private bool invoiceAmountFieldSpecified;
    
    private string invoiceCodeField;
    
    private string invoiceDateField;
    
    private int invoiceIdField;
    
    private bool invoiceIdFieldSpecified;
    
    private string invoiceTypeField;
    
    private Customer payerField;
    
    private Position[] positionsField;
    
    private Problem[] problemsLightField;
    
    private Problem[] problemsSevereField;
    
    private int repairOrderNumberField;
    
    private bool repairOrderNumberFieldSpecified;
    
    private string requestTypeField;
    
    private string salesPersonIdField;
    
    private string salesPersonNameField;
    
    private string teamField;
    
    private string vehicleBatteryBuyField;
    
    private string vehicleBatteryIdField;
    
    private string vehicleCommercialTypeField;
    
    private string vehicleFuelTypeField;
    
    private string vehicleMakeField;
    
    private int vehicleMilageField;
    
    private bool vehicleMilageFieldSpecified;
    
    private string vehicleNextCheckDateField;
    
    private string vehicleRegistrationNumberField;
    
    private string vehicleTechnicalTypeField;
    
    private string vehicleTypeField;
    
    private string vehicleTypeDescriptionField;
    
    private string vehicleTypeDescriptionLongField;
    
    private string vehicleVINField;
    
    private string vehicleYearField;
    
    private string workingAreaField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Customer customer {
        get {
            return this.customerField;
        }
        set {
            this.customerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string errorCode {
        get {
            return this.errorCodeField;
        }
        set {
            this.errorCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string errorText {
        get {
            return this.errorTextField;
        }
        set {
            this.errorTextField = value;
        }
    }
    
    /// <remarks/>
    public double invoiceAmount {
        get {
            return this.invoiceAmountField;
        }
        set {
            this.invoiceAmountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool invoiceAmountSpecified {
        get {
            return this.invoiceAmountFieldSpecified;
        }
        set {
            this.invoiceAmountFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string invoiceCode {
        get {
            return this.invoiceCodeField;
        }
        set {
            this.invoiceCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string invoiceDate {
        get {
            return this.invoiceDateField;
        }
        set {
            this.invoiceDateField = value;
        }
    }
    
    /// <remarks/>
    public int invoiceId {
        get {
            return this.invoiceIdField;
        }
        set {
            this.invoiceIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool invoiceIdSpecified {
        get {
            return this.invoiceIdFieldSpecified;
        }
        set {
            this.invoiceIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string invoiceType {
        get {
            return this.invoiceTypeField;
        }
        set {
            this.invoiceTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Customer payer {
        get {
            return this.payerField;
        }
        set {
            this.payerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("positions", IsNullable=true)]
    public Position[] positions {
        get {
            return this.positionsField;
        }
        set {
            this.positionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("problemsLight", IsNullable=true)]
    public Problem[] problemsLight {
        get {
            return this.problemsLightField;
        }
        set {
            this.problemsLightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("problemsSevere", IsNullable=true)]
    public Problem[] problemsSevere {
        get {
            return this.problemsSevereField;
        }
        set {
            this.problemsSevereField = value;
        }
    }
    
    /// <remarks/>
    public int repairOrderNumber {
        get {
            return this.repairOrderNumberField;
        }
        set {
            this.repairOrderNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool repairOrderNumberSpecified {
        get {
            return this.repairOrderNumberFieldSpecified;
        }
        set {
            this.repairOrderNumberFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string requestType {
        get {
            return this.requestTypeField;
        }
        set {
            this.requestTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string salesPersonId {
        get {
            return this.salesPersonIdField;
        }
        set {
            this.salesPersonIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string salesPersonName {
        get {
            return this.salesPersonNameField;
        }
        set {
            this.salesPersonNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string team {
        get {
            return this.teamField;
        }
        set {
            this.teamField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string vehicleBatteryBuy {
        get {
            return this.vehicleBatteryBuyField;
        }
        set {
            this.vehicleBatteryBuyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string vehicleBatteryId {
        get {
            return this.vehicleBatteryIdField;
        }
        set {
            this.vehicleBatteryIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string vehicleCommercialType {
        get {
            return this.vehicleCommercialTypeField;
        }
        set {
            this.vehicleCommercialTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string vehicleFuelType {
        get {
            return this.vehicleFuelTypeField;
        }
        set {
            this.vehicleFuelTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string vehicleMake {
        get {
            return this.vehicleMakeField;
        }
        set {
            this.vehicleMakeField = value;
        }
    }
    
    /// <remarks/>
    public int vehicleMilage {
        get {
            return this.vehicleMilageField;
        }
        set {
            this.vehicleMilageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool vehicleMilageSpecified {
        get {
            return this.vehicleMilageFieldSpecified;
        }
        set {
            this.vehicleMilageFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string vehicleNextCheckDate {
        get {
            return this.vehicleNextCheckDateField;
        }
        set {
            this.vehicleNextCheckDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string vehicleRegistrationNumber {
        get {
            return this.vehicleRegistrationNumberField;
        }
        set {
            this.vehicleRegistrationNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string vehicleTechnicalType {
        get {
            return this.vehicleTechnicalTypeField;
        }
        set {
            this.vehicleTechnicalTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string vehicleType {
        get {
            return this.vehicleTypeField;
        }
        set {
            this.vehicleTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string vehicleTypeDescription {
        get {
            return this.vehicleTypeDescriptionField;
        }
        set {
            this.vehicleTypeDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string vehicleTypeDescriptionLong {
        get {
            return this.vehicleTypeDescriptionLongField;
        }
        set {
            this.vehicleTypeDescriptionLongField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string vehicleVIN {
        get {
            return this.vehicleVINField;
        }
        set {
            this.vehicleVINField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string vehicleYear {
        get {
            return this.vehicleYearField;
        }
        set {
            this.vehicleYearField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string workingArea {
        get {
            return this.workingAreaField;
        }
        set {
            this.workingAreaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dataobjects.vega.vector.at/xsd")]
public partial class Customer {
    
    private string birthDateField;
    
    private string cityField;
    
    private string eMail1Field;
    
    private string eMail2Field;
    
    private string firstNameField;
    
    private System.Nullable<int> idField;
    
    private bool idFieldSpecified;
    
    private string lastNameField;
    
    private string marketingCommentField;
    
    private string marketingEMailField;
    
    private string marketingFaxField;
    
    private string marketingMailField;
    
    private string marketingPhoneField;
    
    private string marketingPreferredField;
    
    private string marketingSMSMMSField;
    
    private string marketingWelcomeTerminalField;
    
    private string mobilePhone1Field;
    
    private string mobilePhone2Field;
    
    private string nameField;
    
    private string phone1Field;
    
    private string phone2Field;
    
    private string sexField;
    
    private string streetField;
    
    private string taxNumberField;
    
    private bool taxPayerField;
    
    private bool taxPayerFieldSpecified;
    
    private bool useMaketingDataField;
    
    private bool useMaketingDataFieldSpecified;
    
    private string zipField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string birthDate {
        get {
            return this.birthDateField;
        }
        set {
            this.birthDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string city {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string eMail1 {
        get {
            return this.eMail1Field;
        }
        set {
            this.eMail1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string eMail2 {
        get {
            return this.eMail2Field;
        }
        set {
            this.eMail2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string firstName {
        get {
            return this.firstNameField;
        }
        set {
            this.firstNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idSpecified {
        get {
            return this.idFieldSpecified;
        }
        set {
            this.idFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string lastName {
        get {
            return this.lastNameField;
        }
        set {
            this.lastNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string marketingComment {
        get {
            return this.marketingCommentField;
        }
        set {
            this.marketingCommentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string marketingEMail {
        get {
            return this.marketingEMailField;
        }
        set {
            this.marketingEMailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string marketingFax {
        get {
            return this.marketingFaxField;
        }
        set {
            this.marketingFaxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string marketingMail {
        get {
            return this.marketingMailField;
        }
        set {
            this.marketingMailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string marketingPhone {
        get {
            return this.marketingPhoneField;
        }
        set {
            this.marketingPhoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string marketingPreferred {
        get {
            return this.marketingPreferredField;
        }
        set {
            this.marketingPreferredField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string marketingSMSMMS {
        get {
            return this.marketingSMSMMSField;
        }
        set {
            this.marketingSMSMMSField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string marketingWelcomeTerminal {
        get {
            return this.marketingWelcomeTerminalField;
        }
        set {
            this.marketingWelcomeTerminalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string mobilePhone1 {
        get {
            return this.mobilePhone1Field;
        }
        set {
            this.mobilePhone1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string mobilePhone2 {
        get {
            return this.mobilePhone2Field;
        }
        set {
            this.mobilePhone2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string phone1 {
        get {
            return this.phone1Field;
        }
        set {
            this.phone1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string phone2 {
        get {
            return this.phone2Field;
        }
        set {
            this.phone2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string sex {
        get {
            return this.sexField;
        }
        set {
            this.sexField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string street {
        get {
            return this.streetField;
        }
        set {
            this.streetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string taxNumber {
        get {
            return this.taxNumberField;
        }
        set {
            this.taxNumberField = value;
        }
    }
    
    /// <remarks/>
    public bool taxPayer {
        get {
            return this.taxPayerField;
        }
        set {
            this.taxPayerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool taxPayerSpecified {
        get {
            return this.taxPayerFieldSpecified;
        }
        set {
            this.taxPayerFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool useMaketingData {
        get {
            return this.useMaketingDataField;
        }
        set {
            this.useMaketingDataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool useMaketingDataSpecified {
        get {
            return this.useMaketingDataFieldSpecified;
        }
        set {
            this.useMaketingDataFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string zip {
        get {
            return this.zipField;
        }
        set {
            this.zipField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dataobjects.vega.vector.at/xsd")]
public partial class UserInfo {
    
    private string birNumberField;
    
    private int companyIdField;
    
    private bool companyIdFieldSpecified;
    
    private string dataGroupField;
    
    private string errorMessageField;
    
    private string siteCodeField;
    
    private string userNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string birNumber {
        get {
            return this.birNumberField;
        }
        set {
            this.birNumberField = value;
        }
    }
    
    /// <remarks/>
    public int companyId {
        get {
            return this.companyIdField;
        }
        set {
            this.companyIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool companyIdSpecified {
        get {
            return this.companyIdFieldSpecified;
        }
        set {
            this.companyIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string dataGroup {
        get {
            return this.dataGroupField;
        }
        set {
            this.dataGroupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string errorMessage {
        get {
            return this.errorMessageField;
        }
        set {
            this.errorMessageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string siteCode {
        get {
            return this.siteCodeField;
        }
        set {
            this.siteCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string userName {
        get {
            return this.userNameField;
        }
        set {
            this.userNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dataobjects.vega.vector.at/xsd")]
public partial class Problem {
    
    private string problemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string problem {
        get {
            return this.problemField;
        }
        set {
            this.problemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dataobjects.vega.vector.at/xsd")]
public partial class Position {
    
    private string codeField;
    
    private string descirptionField;
    
    private double labourTimeField;
    
    private bool labourTimeFieldSpecified;
    
    private string labourTimeTypeField;
    
    private string partDescriptionField;
    
    private string partFamilyField;
    
    private double priceField;
    
    private bool priceFieldSpecified;
    
    private double priceFinalField;
    
    private bool priceFinalFieldSpecified;
    
    private string typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string descirption {
        get {
            return this.descirptionField;
        }
        set {
            this.descirptionField = value;
        }
    }
    
    /// <remarks/>
    public double labourTime {
        get {
            return this.labourTimeField;
        }
        set {
            this.labourTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool labourTimeSpecified {
        get {
            return this.labourTimeFieldSpecified;
        }
        set {
            this.labourTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string labourTimeType {
        get {
            return this.labourTimeTypeField;
        }
        set {
            this.labourTimeTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string partDescription {
        get {
            return this.partDescriptionField;
        }
        set {
            this.partDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string partFamily {
        get {
            return this.partFamilyField;
        }
        set {
            this.partFamilyField = value;
        }
    }
    
    /// <remarks/>
    public double price {
        get {
            return this.priceField;
        }
        set {
            this.priceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool priceSpecified {
        get {
            return this.priceFieldSpecified;
        }
        set {
            this.priceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public double priceFinal {
        get {
            return this.priceFinalField;
        }
        set {
            this.priceFinalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool priceFinalSpecified {
        get {
            return this.priceFinalFieldSpecified;
        }
        set {
            this.priceFinalFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}
