#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VegaHitAutoWebService.LinqClasses
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ICARDMS")]
	public partial class CustomerDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public CustomerDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ICARDMSConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CustomerDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CustomerDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CustomerDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CustomerDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<_RI_Vega_Customer> _RI_Vega_Customers
		{
			get
			{
				return this.GetTable<_RI_Vega_Customer>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[_RI_Vega_Customer]")]
	public partial class _RI_Vega_Customer
	{
		
		private System.DateTime _birthDate;
		
		private string _City;
		
		private string _eMAil1;
		
		private string _eMail2;
		
		private string _FirstName;
		
		private decimal _ID;
		
		private string _lastName;
		
		private string _marketingComment;
		
		private string _marketingEMail;
		
		private string _marketingFax;
		
		private string _marketingMail;
		
		private string _marketingPhone;
		
		private string _marketingPreferred;
		
		private short _marketingSMSMMS;
		
		private string _marketingWelcomeTerminal;
		
		private string _mobilePhone1;
		
		private string _mobilePhone2;
		
		private string _name;
		
		private string _Phone1;
		
		private string _Phone2;
		
		private short _Sex;
		
		private string _Street;
		
		private string _TaxNumber;
		
		private string _TaxPayer;
		
		private string _ZipCide;
		
		public _RI_Vega_Customer()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birthDate", DbType="DateTime NOT NULL")]
		public System.DateTime birthDate
		{
			get
			{
				return this._birthDate;
			}
			set
			{
				if ((this._birthDate != value))
				{
					this._birthDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(25)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this._City = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eMAil1", DbType="VarChar(64)")]
		public string eMAil1
		{
			get
			{
				return this._eMAil1;
			}
			set
			{
				if ((this._eMAil1 != value))
				{
					this._eMAil1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eMail2", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string eMail2
		{
			get
			{
				return this._eMail2;
			}
			set
			{
				if ((this._eMail2 != value))
				{
					this._eMail2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="VarChar(20)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this._FirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Decimal(10,0) NOT NULL")]
		public decimal ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastName", DbType="VarChar(25)")]
		public string lastName
		{
			get
			{
				return this._lastName;
			}
			set
			{
				if ((this._lastName != value))
				{
					this._lastName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_marketingComment", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string marketingComment
		{
			get
			{
				return this._marketingComment;
			}
			set
			{
				if ((this._marketingComment != value))
				{
					this._marketingComment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_marketingEMail", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string marketingEMail
		{
			get
			{
				return this._marketingEMail;
			}
			set
			{
				if ((this._marketingEMail != value))
				{
					this._marketingEMail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_marketingFax", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string marketingFax
		{
			get
			{
				return this._marketingFax;
			}
			set
			{
				if ((this._marketingFax != value))
				{
					this._marketingFax = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_marketingMail", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string marketingMail
		{
			get
			{
				return this._marketingMail;
			}
			set
			{
				if ((this._marketingMail != value))
				{
					this._marketingMail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_marketingPhone", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string marketingPhone
		{
			get
			{
				return this._marketingPhone;
			}
			set
			{
				if ((this._marketingPhone != value))
				{
					this._marketingPhone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_marketingPreferred", DbType="VarChar(1)")]
		public string marketingPreferred
		{
			get
			{
				return this._marketingPreferred;
			}
			set
			{
				if ((this._marketingPreferred != value))
				{
					this._marketingPreferred = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_marketingSMSMMS", DbType="SmallInt NOT NULL")]
		public short marketingSMSMMS
		{
			get
			{
				return this._marketingSMSMMS;
			}
			set
			{
				if ((this._marketingSMSMMS != value))
				{
					this._marketingSMSMMS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_marketingWelcomeTerminal", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string marketingWelcomeTerminal
		{
			get
			{
				return this._marketingWelcomeTerminal;
			}
			set
			{
				if ((this._marketingWelcomeTerminal != value))
				{
					this._marketingWelcomeTerminal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mobilePhone1", DbType="VarChar(15)")]
		public string mobilePhone1
		{
			get
			{
				return this._mobilePhone1;
			}
			set
			{
				if ((this._mobilePhone1 != value))
				{
					this._mobilePhone1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mobilePhone2", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string mobilePhone2
		{
			get
			{
				return this._mobilePhone2;
			}
			set
			{
				if ((this._mobilePhone2 != value))
				{
					this._mobilePhone2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(123)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone1", DbType="VarChar(15)")]
		public string Phone1
		{
			get
			{
				return this._Phone1;
			}
			set
			{
				if ((this._Phone1 != value))
				{
					this._Phone1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone2", DbType="VarChar(15)")]
		public string Phone2
		{
			get
			{
				return this._Phone2;
			}
			set
			{
				if ((this._Phone2 != value))
				{
					this._Phone2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sex", DbType="SmallInt NOT NULL")]
		public short Sex
		{
			get
			{
				return this._Sex;
			}
			set
			{
				if ((this._Sex != value))
				{
					this._Sex = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Street", DbType="VarChar(30)")]
		public string Street
		{
			get
			{
				return this._Street;
			}
			set
			{
				if ((this._Street != value))
				{
					this._Street = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxNumber", DbType="VarChar(15)")]
		public string TaxNumber
		{
			get
			{
				return this._TaxNumber;
			}
			set
			{
				if ((this._TaxNumber != value))
				{
					this._TaxNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxPayer", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string TaxPayer
		{
			get
			{
				return this._TaxPayer;
			}
			set
			{
				if ((this._TaxPayer != value))
				{
					this._TaxPayer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZipCide", DbType="VarChar(10)")]
		public string ZipCide
		{
			get
			{
				return this._ZipCide;
			}
			set
			{
				if ((this._ZipCide != value))
				{
					this._ZipCide = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
