<?xml version="1.0" encoding="utf-8"?><Database Name="ICARDMS" Class="PositionDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DC2\icardms;Initial Catalog=ICARDMS;User ID=kasa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ICARDMSConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[_RI_Vega_Positions]" Member="_RI_Vega_Positions">
    <Type Name="_RI_Vega_Position">
      <Column Name="numintOt" Type="System.Decimal" DbType="Decimal(10,0) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="labourTime" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="labourTimeType" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="partFamily" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="price" Type="System.Decimal" DbType="Decimal(12,2)" CanBeNull="true" />
      <Column Name="priceFinal" Type="System.Decimal" DbType="Decimal(20,8)" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>