#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VegaHitAutoWebService.LinqClasses
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ICARDMS")]
	public partial class PositionDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public PositionDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ICARDMSConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PositionDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PositionDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PositionDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PositionDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<_RI_Vega_Position> _RI_Vega_Positions
		{
			get
			{
				return this.GetTable<_RI_Vega_Position>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[_RI_Vega_Positions]")]
	public partial class _RI_Vega_Position
	{
		
		private decimal _numintOt;
		
		private string _Code;
		
		private string _Description;
		
		private System.Nullable<decimal> _labourTime;
		
		private string _labourTimeType;
		
		private string _partFamily;
		
		private System.Nullable<decimal> _price;
		
		private System.Nullable<decimal> _priceFinal;
		
		private string _Type;
		
		public _RI_Vega_Position()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numintOt", DbType="Decimal(10,0) NOT NULL")]
		public decimal numintOt
		{
			get
			{
				return this._numintOt;
			}
			set
			{
				if ((this._numintOt != value))
				{
					this._numintOt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="Char(20) NOT NULL", CanBeNull=false)]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_labourTime", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> labourTime
		{
			get
			{
				return this._labourTime;
			}
			set
			{
				if ((this._labourTime != value))
				{
					this._labourTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_labourTimeType", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string labourTimeType
		{
			get
			{
				return this._labourTimeType;
			}
			set
			{
				if ((this._labourTimeType != value))
				{
					this._labourTimeType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_partFamily", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string partFamily
		{
			get
			{
				return this._partFamily;
			}
			set
			{
				if ((this._partFamily != value))
				{
					this._partFamily = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Decimal(12,2)")]
		public System.Nullable<decimal> price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this._price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_priceFinal", DbType="Decimal(20,8)")]
		public System.Nullable<decimal> priceFinal
		{
			get
			{
				return this._priceFinal;
			}
			set
			{
				if ((this._priceFinal != value))
				{
					this._priceFinal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this._Type = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
