<?xml version="1.0" encoding="utf-8"?><Database Name="ICARDMS" Class="VehicleInvoiceDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=192.168.0.7\icardms;Initial Catalog=ICARDMS;User ID=kasa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ICARDMSConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="_RI_Vega_VehicleData" Member="_RI_Vega_VehicleDatas">
    <Type Name="_RI_Vega_VehicleData">
      <Column Name="ErrorCode" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="Errortext" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="InvoiceAmount" Type="System.Decimal" DbType="Decimal(12,2)" CanBeNull="true" />
      <Column Name="InvoiceCode" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="Invoicedate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="InvoiceID" Type="System.Decimal" DbType="Decimal(8,0)" CanBeNull="true" />
      <Column Name="Inovicetype" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="[_payer]" Member="_payer" Type="System.Decimal" DbType="Decimal(10,0)" CanBeNull="true" />
      <Column Name="[_positions]" Member="_positions" Type="System.Decimal" DbType="Decimal(10,0) NOT NULL" CanBeNull="false" />
      <Column Name="problemsLight" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="problemsSevere" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="repairOrderNumber" Type="System.Decimal" DbType="Decimal(8,0)" CanBeNull="true" />
      <Column Name="requestType" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="salesPersionId" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="salesPersonName" Type="System.String" DbType="Char(25)" CanBeNull="true" />
      <Column Name="Team" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="vehicleBatteryBuy" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="vehicleBatteryId" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="vehicleCommercialType" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="vehicleFuelType" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="vehicleMake" Type="System.String" DbType="Char(4)" CanBeNull="true" />
      <Column Name="vehicleMilage" Type="System.Decimal" DbType="Decimal(8,0)" CanBeNull="true" />
      <Column Name="vehicleNextCheckDate" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="vehicleRegistrationNumber" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="vehicleTechnicalType" Type="System.String" DbType="Char(25)" CanBeNull="true" />
      <Column Name="vehicleType" Type="System.String" DbType="Char(8)" CanBeNull="true" />
      <Column Name="vehicleTypeDescription" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="vehicleTypeDescriptionLong" Type="System.String" DbType="VarChar(75)" CanBeNull="true" />
      <Column Name="vehicleVIN" Type="System.String" DbType="Char(17)" CanBeNull="true" />
      <Column Name="vehicleYear" Type="System.Decimal" DbType="Decimal(4,0)" CanBeNull="true" />
      <Column Name="workingArea" Type="System.String" DbType="Char(3)" CanBeNull="true" />
    </Type>
  </Table>
</Database>