#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VegaHitAutoWebService.LinqClasses
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ICARDMS")]
	public partial class VehicleInvoiceDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public VehicleInvoiceDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ICARDMSConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public VehicleInvoiceDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VehicleInvoiceDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VehicleInvoiceDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VehicleInvoiceDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<_RI_Vega_VehicleData> _RI_Vega_VehicleDatas
		{
			get
			{
				return this.GetTable<_RI_Vega_VehicleData>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute()]
	public partial class _RI_Vega_VehicleData
	{
		
		private string _ErrorCode;
		
		private string _Errortext;
		
		private System.Nullable<decimal> _InvoiceAmount;
		
		private string _InvoiceCode;
		
		private System.Nullable<System.DateTime> _Invoicedate;
		
		private System.Nullable<decimal> _InvoiceID;
		
		private string _Inovicetype;
		
		private System.Nullable<decimal> @__payer;
		
		private decimal @__positions;
		
		private string _problemsLight;
		
		private string _problemsSevere;
		
		private System.Nullable<decimal> _repairOrderNumber;
		
		private string _requestType;
		
		private string _salesPersionId;
		
		private string _salesPersonName;
		
		private string _Team;
		
		private string _vehicleBatteryBuy;
		
		private string _vehicleBatteryId;
		
		private string _vehicleCommercialType;
		
		private string _vehicleFuelType;
		
		private string _vehicleMake;
		
		private System.Nullable<decimal> _vehicleMilage;
		
		private string _vehicleNextCheckDate;
		
		private string _vehicleRegistrationNumber;
		
		private string _vehicleTechnicalType;
		
		private string _vehicleType;
		
		private string _vehicleTypeDescription;
		
		private string _vehicleTypeDescriptionLong;
		
		private string _vehicleVIN;
		
		private System.Nullable<decimal> _vehicleYear;
		
		private string _workingArea;
		
		public _RI_Vega_VehicleData()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorCode", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string ErrorCode
		{
			get
			{
				return this._ErrorCode;
			}
			set
			{
				if ((this._ErrorCode != value))
				{
					this._ErrorCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Errortext", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string Errortext
		{
			get
			{
				return this._Errortext;
			}
			set
			{
				if ((this._Errortext != value))
				{
					this._Errortext = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceAmount", DbType="Decimal(12,2)")]
		public System.Nullable<decimal> InvoiceAmount
		{
			get
			{
				return this._InvoiceAmount;
			}
			set
			{
				if ((this._InvoiceAmount != value))
				{
					this._InvoiceAmount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceCode", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string InvoiceCode
		{
			get
			{
				return this._InvoiceCode;
			}
			set
			{
				if ((this._InvoiceCode != value))
				{
					this._InvoiceCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Invoicedate", DbType="DateTime")]
		public System.Nullable<System.DateTime> Invoicedate
		{
			get
			{
				return this._Invoicedate;
			}
			set
			{
				if ((this._Invoicedate != value))
				{
					this._Invoicedate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceID", DbType="Decimal(8,0)")]
		public System.Nullable<decimal> InvoiceID
		{
			get
			{
				return this._InvoiceID;
			}
			set
			{
				if ((this._InvoiceID != value))
				{
					this._InvoiceID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Inovicetype", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string Inovicetype
		{
			get
			{
				return this._Inovicetype;
			}
			set
			{
				if ((this._Inovicetype != value))
				{
					this._Inovicetype = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_payer]", Storage="__payer", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> _payer
		{
			get
			{
				return this.@__payer;
			}
			set
			{
				if ((this.@__payer != value))
				{
					this.@__payer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_positions]", Storage="__positions", DbType="Decimal(10,0) NOT NULL")]
		public decimal _positions
		{
			get
			{
				return this.@__positions;
			}
			set
			{
				if ((this.@__positions != value))
				{
					this.@__positions = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_problemsLight", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string problemsLight
		{
			get
			{
				return this._problemsLight;
			}
			set
			{
				if ((this._problemsLight != value))
				{
					this._problemsLight = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_problemsSevere", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string problemsSevere
		{
			get
			{
				return this._problemsSevere;
			}
			set
			{
				if ((this._problemsSevere != value))
				{
					this._problemsSevere = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_repairOrderNumber", DbType="Decimal(8,0)")]
		public System.Nullable<decimal> repairOrderNumber
		{
			get
			{
				return this._repairOrderNumber;
			}
			set
			{
				if ((this._repairOrderNumber != value))
				{
					this._repairOrderNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_requestType", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string requestType
		{
			get
			{
				return this._requestType;
			}
			set
			{
				if ((this._requestType != value))
				{
					this._requestType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salesPersionId", DbType="VarChar(4)")]
		public string salesPersionId
		{
			get
			{
				return this._salesPersionId;
			}
			set
			{
				if ((this._salesPersionId != value))
				{
					this._salesPersionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salesPersonName", DbType="Char(25)")]
		public string salesPersonName
		{
			get
			{
				return this._salesPersonName;
			}
			set
			{
				if ((this._salesPersonName != value))
				{
					this._salesPersonName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Team", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string Team
		{
			get
			{
				return this._Team;
			}
			set
			{
				if ((this._Team != value))
				{
					this._Team = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vehicleBatteryBuy", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string vehicleBatteryBuy
		{
			get
			{
				return this._vehicleBatteryBuy;
			}
			set
			{
				if ((this._vehicleBatteryBuy != value))
				{
					this._vehicleBatteryBuy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vehicleBatteryId", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string vehicleBatteryId
		{
			get
			{
				return this._vehicleBatteryId;
			}
			set
			{
				if ((this._vehicleBatteryId != value))
				{
					this._vehicleBatteryId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vehicleCommercialType", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string vehicleCommercialType
		{
			get
			{
				return this._vehicleCommercialType;
			}
			set
			{
				if ((this._vehicleCommercialType != value))
				{
					this._vehicleCommercialType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vehicleFuelType", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string vehicleFuelType
		{
			get
			{
				return this._vehicleFuelType;
			}
			set
			{
				if ((this._vehicleFuelType != value))
				{
					this._vehicleFuelType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vehicleMake", DbType="Char(4)")]
		public string vehicleMake
		{
			get
			{
				return this._vehicleMake;
			}
			set
			{
				if ((this._vehicleMake != value))
				{
					this._vehicleMake = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vehicleMilage", DbType="Decimal(8,0)")]
		public System.Nullable<decimal> vehicleMilage
		{
			get
			{
				return this._vehicleMilage;
			}
			set
			{
				if ((this._vehicleMilage != value))
				{
					this._vehicleMilage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vehicleNextCheckDate", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string vehicleNextCheckDate
		{
			get
			{
				return this._vehicleNextCheckDate;
			}
			set
			{
				if ((this._vehicleNextCheckDate != value))
				{
					this._vehicleNextCheckDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vehicleRegistrationNumber", DbType="NChar(10)")]
		public string vehicleRegistrationNumber
		{
			get
			{
				return this._vehicleRegistrationNumber;
			}
			set
			{
				if ((this._vehicleRegistrationNumber != value))
				{
					this._vehicleRegistrationNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vehicleTechnicalType", DbType="Char(25)")]
		public string vehicleTechnicalType
		{
			get
			{
				return this._vehicleTechnicalType;
			}
			set
			{
				if ((this._vehicleTechnicalType != value))
				{
					this._vehicleTechnicalType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vehicleType", DbType="Char(8)")]
		public string vehicleType
		{
			get
			{
				return this._vehicleType;
			}
			set
			{
				if ((this._vehicleType != value))
				{
					this._vehicleType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vehicleTypeDescription", DbType="VarChar(20)")]
		public string vehicleTypeDescription
		{
			get
			{
				return this._vehicleTypeDescription;
			}
			set
			{
				if ((this._vehicleTypeDescription != value))
				{
					this._vehicleTypeDescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vehicleTypeDescriptionLong", DbType="VarChar(75)")]
		public string vehicleTypeDescriptionLong
		{
			get
			{
				return this._vehicleTypeDescriptionLong;
			}
			set
			{
				if ((this._vehicleTypeDescriptionLong != value))
				{
					this._vehicleTypeDescriptionLong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vehicleVIN", DbType="Char(17)")]
		public string vehicleVIN
		{
			get
			{
				return this._vehicleVIN;
			}
			set
			{
				if ((this._vehicleVIN != value))
				{
					this._vehicleVIN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vehicleYear", DbType="Decimal(4,0)")]
		public System.Nullable<decimal> vehicleYear
		{
			get
			{
				return this._vehicleYear;
			}
			set
			{
				if ((this._vehicleYear != value))
				{
					this._vehicleYear = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_workingArea", DbType="Char(3)")]
		public string workingArea
		{
			get
			{
				return this._workingArea;
			}
			set
			{
				if ((this._workingArea != value))
				{
					this._workingArea = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
